version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.10
    - 2.5.9
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: next
    versions:
    - 10.0.9
    - 10.1.3
    - 9.3.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 16.14.0
    - 17.0.2
  - dependency-name: apollo-server-core
    versions:
    - 2.19.2
    - 2.21.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: "@apollo/react-hooks"
    versions:
    - 4.0.0
  - dependency-name: "@apollo/react-ssr"
    versions:
    - 4.0.0
  - dependency-name: apollo-server-micro
    versions:
    - 2.14.2
  - dependency-name: react-apollo
    versions:
    - 3.1.5
  - dependency-name: apollo-link
    versions:
    - 1.2.14
  - dependency-name: apollo-link-schema
    versions:
    - 1.2.5
  - dependency-name: "@apollo/react-common"
    versions:
    - 3.1.4
